# Generated by Django 5.2 on 2025-04-26 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
                ('candle_size', models.CharField(max_length=10)),
                ('log_type', models.CharField(max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=4)),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField()),
                ('take_profit', models.FloatField()),
                ('opened_at', models.CharField(max_length=40)),
                ('closed_at', models.CharField(blank=True, max_length=40, null=True)),
                ('leverage', models.FloatField()),
                ('profit_loss', models.CharField(blank=True, max_length=4, null=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.coin')),
            ],
        ),
    ]
