# Generated by Django 5.2 on 2025-04-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='log_type',
            field=models.CharField(max_length=40),
        ),
    ]
