# Generated by Django 5.2 on 2025-04-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_alter_tradelog_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelog',
            name='coin_tag',
            field=models.CharField(default='BTC', max_length=40),
            preserve_default=False,
        ),
    ]
