# Generated by Django 5.2 on 2025-04-28 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_tradelog_coin_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle_stick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.CharField(max_length=40)),
                ('high', models.CharField(max_length=40)),
                ('low', models.CharField(max_length=40)),
                ('close', models.CharField(max_length=40)),
                ('open_time', models.CharField(max_length=40)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.coin')),
            ],
        ),
    ]
