# Generated by Django 5.2 on 2025-05-09 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_candle_stick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='log_type',
        ),
        migrations.AddField(
            model_name='candle_stick',
            name='is_demand_orderblock',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='candle_stick',
            name='is_inefficient',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='candle_stick',
            name='is_supply_orderblock',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='candle_stick',
            name='is_unmitigated',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='log_type',
            field=models.CharField(default='back_testing', max_length=40),
        ),
        migrations.AlterField(
            model_name='candle_stick',
            name='close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='candle_stick',
            name='high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='candle_stick',
            name='low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='candle_stick',
            name='open',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='candle_stick',
            name='open_time',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Entry_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=40)),
                ('entry_price', models.FloatField()),
                ('take_profit', models.FloatField()),
                ('stop_loss', models.FloatField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.coin')),
            ],
        ),
    ]
