# Generated by Django 5.2 on 2025-05-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_remove_coin_log_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candle_stick',
            name='is_demand_orderblock',
        ),
        migrations.RemoveField(
            model_name='candle_stick',
            name='is_inefficient',
        ),
        migrations.RemoveField(
            model_name='candle_stick',
            name='is_supply_orderblock',
        ),
        migrations.RemoveField(
            model_name='candle_stick',
            name='is_unmitigated',
        ),
        migrations.RemoveField(
            model_name='tradelog',
            name='leverage',
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='closed_at',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='opened_at',
            field=models.FloatField(),
        ),
    ]
