# Generated by Django 5.2 on 2025-05-16 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_remove_candle_stick_is_demand_orderblock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.FloatField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.coin')),
            ],
        ),
    ]
