# Generated by Django 5.2 on 2025-05-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_order_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_point',
            name='tag',
            field=models.CharField(default='BTC', max_length=40),
            preserve_default=False,
        ),
    ]
